### ISSUE TITLE
Javascript errors in Firefox 62, Chrome 69.0.3497.100, Edge

### ISSUE THREAD

**Issue by blitzcrg** [Asmor/5e-monsters#153]
https://kobold.club/fight page doesn't load - just a blank page. First noticed this two weeks ago, and assumed it was an issue with my home network (I have a few...extra security measures in place) and I've since done everything I can to eliminate that as a variable, as well as the usual delete local storage/cookies/etc. 

Error from console:

lodash.min.js:1 Failed to load resource: net::ERR_NAME_RESOLUTION_FAILED
jquery-3.1.1.js:3846 jQuery.Deferred exception: _ is not defined ReferenceError: _ is not defined
    at Object.hasKey (http://kobold.club/fight/js/app-93dd2e4e6b.js:3307:5)
    at thaw (http://kobold.club/fight/js/app-93dd2e4e6b.js:2552:14)
    at Object.initialize (http://kobold.club/fight/js/app-93dd2e4e6b.js:2537:4)
    at serviceInitialization (http://kobold.club/fight/js/app-93dd2e4e6b.js:28:13)
    at Object.invoke (http://kobold.club/fight/thirdparty/angular/angular.js:4762:19)
    at http://kobold.club/fight/thirdparty/angular/angular.js:4569:62
    at forEach (http://kobold.club/fight/thirdparty/angular/angular.js:325:20)
    at createInjector (http://kobold.club/fight/thirdparty/angular/angular.js:4569:3)
    at doBootstrap (http://kobold.club/fight/thirdparty/angular/angular.js:1803:20)
    at bootstrap (http://kobold.club/fight/thirdparty/angular/angular.js:1824:12) undefined
jQuery.Deferred.exceptionHook @ jquery-3.1.1.js:3846
jquery-3.1.1.js:3855 Uncaught ReferenceError: _ is not defined
    at Object.hasKey (app-93dd2e4e6b.js:3307)
    at thaw (app-93dd2e4e6b.js:2552)
    at Object.initialize (app-93dd2e4e6b.js:2537)
    at serviceInitialization (app-93dd2e4e6b.js:28)
    at Object.invoke (angular.js:4762)
    at angular.js:4569
    at forEach (angular.js:325)
    at createInjector (angular.js:4569)
    at doBootstrap (angular.js:1803)
    at bootstrap (angular.js:1824)

**Comment by blitzcrg** [comment]
Woops! Just solved this myself - disabled DNSSEC on my DNS resolver.

So this is potentially an issue, but it's upstream of your project I think.

**Comment by Asmor** [comment]
Yeah, that's being served by a CDN. If it becomes an issue I could always host it locally, but honestly there's nothing on my server (server- or client-side) that's remotely sensitive, so I don't really worry too much about security issues for this site.

Glad you were able to resolve it, and thanks for bringing it to my attention.
