### ISSUE TITLE
Display / source selection issue in Internet Explorer

### ISSUE THREAD

**Issue by ESElrond** [Asmor/5e-monsters#66]
I use the page periodically -- probably once a month or so -- and discovered today that it no longer seems to be functional when loaded using Internet Explorer 11.  I'm running on a desktop PC with Windows 10 64-bit, and a fully-updated copy of IE 11 and this seems to be a recent change (the last time I recall loading the page in IE, it worked fine).

When I load up the site with all filters cleared, the monster selection area is empty.  I noticed that the "Set Sources" menu, when opened, is also empty except for the "Everything", "Core Books", and "None" buttons at the top.  There are no individual sources shown below, and no individual checkboxes.

Pressing any of the three buttons in the "Set Sources" menu has no apparent effect.

I tried flushing my browser cache, and also tried a forced reload of the page -- both before and after clearing the cache -- with no apparent effect.

It seems as though the page still works okay in Chrome and Firefox.

**Comment by Asmor** [comment]
I don't have access to IE 11 to test it, and supporting IE isn't a priority for me.

If someone who cares wants to fix this, I'll happily accept a pull request.

**Comment by snafuy** [comment]
IE 11 error happens here:
TypeError: Object doesn't support property or method 'parseInt'
   at Anonymous function (http://kobold.club/fight/js/app-7de1c12eba.js:1188:5)
   at Monster (http://kobold.club/fight/js/app-7de1c12eba.js:1184:4)
   at Anonymous function (http://kobold.club/fight/js/app-7de1c12eba.js:2265:4)
   at loadMonsters (http://kobold.club/fight/js/app-7de1c12eba.js:2263:3)
   at loadSheet (http://kobold.club/fight/js/app-7de1c12eba.js:2235:4)
   at Anonymous function (http://kobold.club/fight/js/app-7de1c12eba.js:3017:3)
   at processQueue (http://kobold.club/fight/thirdparty/angular/angular.js:16606:11)
   at Anonymous function (http://kobold.club/fight/thirdparty/angular/angular.js:16622:27)
   at Scope.prototype.$eval (http://kobold.club/fight/thirdparty/angular/angular.js:17913:9)
   at Scope.prototype.$digest (http://kobold.club/fight/thirdparty/angular/angular.js:17727:15)

				// Try to parse each of these into a number, but if that fails then just give the
				// original string value, which presumably is either an empty string or something
				// complicated
				var parsed = Number.parseInt(args[key]);

**Comment by snafuy** [comment]
https://stackoverflow.com/questions/28350236/why-use-number-parseint-instead-of-parseint

**Comment by Asmor** [comment]
This should now be fixed. I still don't have easy access to IE11 so I can't test it. If this is still a problem please comment and I'll reopen the issue.
